name: Release binaries

on:
  push:
    branches:
      - '*.*.*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: macos-latest
    name: Release binaries as Github releases
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          cache: true
      - name: setup release environment
        run: |
          echo 'GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}' > .release-env
      - name: release publish
        run: make release
